version: '2'

services:
  flask:
    build: ./flask
    volumes:
      - ./flask:/app
    ports:
      - "5000:5000"

  nginx:
    build: ./nginx
    depends_on:
      - flask
    ports:
      - "0.0.0.0:80:80"

  redis:
    image: redis:latest


  celeryworker:
    build: ./flask
    depends_on:
     - redis
    command: celery -A apps.tasks worker -l INFO

  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5243:5432"

volumes:
  data: {}
